services:
  dev:
    build:
      context:  ./
      dockerfile: Dockerfile.dev
    volumes:
      - ${HOME}/.panoptes/:/root/.panoptes/
      - ${HOME}:${HOME}
    working_dir: ${PWD}

  debug:
    build:
      context:  ./
      dockerfile: Dockerfile.dev
    volumes:
      - ${HOME}/.panoptes/:/root/.panoptes/
      - ${HOME}:${HOME}
    environment:
      - PANOPTES_DEBUG=true
    working_dir: ${PWD}

  stable:
    build:
      context: ./
      dockerfile: Dockerfile.stable
    volumes:
      - ${HOME}/.panoptes/:/root/.panoptes/
      - ${HOME}:${HOME}
    working_dir: ${PWD}
