FROM python:3-alpine

WORKDIR /usr/src/panoptes-cli

RUN apk update && apk add git
RUN pip install git+git://github.com/zooniverse/panoptes-python-client.git

COPY . .

RUN pip install .

ENTRYPOINT [ "panoptes" ]
